### PR TITLE
Unit test api get info user

### PR DESCRIPTION
**Pull request by at-minhdao**
## Description
- Unit test get information of user
## Reference Requirements
- Product Backlog ID: PBI-46
- Task ID: #46.3

## Reference Isuees
#{issue_id}

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

### CODE REVIEW

**Review by at-trampham — COMMENTED** [review]
LGTM

**Review by ghost — CHANGES_REQUESTED** [review]
- miss case user don't login

**Review by ghost — APPROVED** [review]
check conflict.

**Review by ghost — APPROVED** [review]
LGTM

**Pull request merged**
